In [5]:
import scanpy as sc
import numpy as np
import pandas as pd
import os

In [2]:
path_data='/om2/user/khrovati/data/cross_system_integration/'
path_pancreas=path_data+'pancreas_conditions_MIA_HPAP2/'

## Randomly subset pancreas adata

In [3]:
adata=sc.read(path_pancreas+'combined_orthologuesHVG.h5ad')

In [7]:
pd.crosstab(adata.obs.cell_type_eval,adata.obs.system)

system               0      1
cell_type_eval
acinar             480  49361
alpha            40903  50211
alpha+beta         678   4575
alpha+delta       1896      0
beta            102109  37174
beta+delta        5090      0
beta+gamma        1208      0
delta            24663   3648
delta+gamma       1062      0
ductal            8739  23553
endo. prolif.      870    701
endothelial      13468   6894
gamma             6993   1633
immune           31264   2883
schwann            616      0
stellate a.      18132   8064
stellate q.       4969   3506

In [15]:
n=10000
adata_sub=adata[np.random.RandomState(seed=0).permutation(adata.obs_names)[:n],:]
pd.crosstab(adata_sub.obs.cell_type_eval,adata_sub.obs.system)

system             0     1
cell_type_eval
acinar            10  1097
alpha            896  1076
alpha+beta        25   120
alpha+delta       50     0
beta            2286   770
beta+delta       124     0
beta+gamma        21     0
delta            507    72
delta+gamma       18     0
ductal           190   484
endo. prolif.     16    17
endothelial      315   161
gamma            135    39
immune           697    66
schwann           15     0
stellate a.      401   180
stellate q.      117    95

In [26]:
# Save to tutorials directory
adata_sub.write(os.getcwd().split('notebooks/')[0]+'tutorials/data/'+f'mouse-human_pancreas_subset{n}.h5ad')